export interface Climas {
    region:string;
    idRegion:number;
    nombreDia:string;
    temperaturaC:number;
    temperaturaF:number;
    estadoClima:string;
  }
  
  export let ListaClimas:Array<Climas>=[
    {
        region:"Valparaíso",
        idRegion:1,
        nombreDia:"Lunes",
        temperaturaC:20,
        temperaturaF:68,
        estadoClima:"Soleado"
    },
    {
        region:"Valparaíso",
        idRegion:1,
        nombreDia:"Martes",
        temperaturaC:22,
        temperaturaF:71.6,
        estadoClima:"Soleado"
    },
    {
        region:"Valparaíso",
        idRegion:1,
        nombreDia:"Miercoles",
        temperaturaC:19,
        temperaturaF:66.2,
        estadoClima:"Soleado"
    },
    {
        region:"Valparaíso",
        idRegion:1,
        nombreDia:"Jueves",
        temperaturaC:15,
        temperaturaF:59,
        estadoClima:"Nublado"
    },
    {
        region:"Valparaíso",
        idRegion:1,
        nombreDia:"Viernes",
        temperaturaC:12,
        temperaturaF:53.6,
        estadoClima:"Lluvioso"
    },
    {
        region:"Valparaíso",
        idRegion:1,
        nombreDia:"Sabado",
        temperaturaC:9,
        temperaturaF:48.2,
        estadoClima:"Tormenta"
    },
    {
        region:"Valparaíso",
        idRegion:1,
        nombreDia:"Domingo",
        temperaturaC:5,
        temperaturaF:41,
        estadoClima:"Tormenta"
    },
    {
        region:"Talca",
        idRegion:2,
        nombreDia:"Lunes",
        temperaturaC:18,
        temperaturaF:64.4,
        estadoClima:"Soleado"
    },
    {
        region:"Talca",
        idRegion:2,
        nombreDia:"Martes",
        temperaturaC:9,
        temperaturaF:48.2,
        estadoClima:"Lluvioso"
    },
    {
        region:"Talca",
        idRegion:2,
        nombreDia:"Miercoles",
        temperaturaC:11,
        temperaturaF:51.8,
        estadoClima:"Nublado"
    },
    {
        region:"Talca",
        idRegion:2,
        nombreDia:"Jueves",
        temperaturaC:7,
        temperaturaF:44.6,
        estadoClima:"Tormenta"
    },
    {
        region:"Talca",
        idRegion:2,
        nombreDia:"Viernes",
        temperaturaC:22,
        temperaturaF:71.6,
        estadoClima:"Soleado"
    },
    {
        region:"Talca",
        idRegion:2,
        nombreDia:"Sabado",
        temperaturaC:10,
        temperaturaF:50,
        estadoClima:"Lluvioso"
    },
    {
        region:"Talca",
        idRegion:2,
        nombreDia:"Domingo",
        temperaturaC:7,
        temperaturaF:44.6,
        estadoClima:"Tormenta"
    },
  ];